server:
  port: 9080
  servlet:
    context-path: /local
spring:
  application:
    name: web_service
  #profiles:
    #active: dev
  main:
    allow-allow-circular-reference: true

#2.数据库连接参数
#2.1jdbc驱动，示数据库厂商决定，这是mysql的驱动
jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://192.168.79.253:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&serverTimezone=GMT%2B8
  username: root
  password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9099/eureka
    register-with-eureka: true
    fetch-registry: true
#3.Mybatis配置
#3.1 mybatis配置文件所在路径
mybatis_config_file: mybatis-config.xml

#3.2 mapper文件所在路径，这样写可匹配mapper目录下的所有mapper，包括其子目录下的
mapper_path: com/example/dao/**/*Mapper.xml

#3.3 entity所在包
entity_package: com.example.entity

#分页插件
pagehelper:
  helper-dialect: mysql
  params:
    count: countSql
  reasonable: true
  support-methods-arguments: true

logging:
  config:
    classpath: logback.xml


